# Generated by Django 5.2.8 on 2025-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_store_platform'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_status'], name='user_subscription_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store_platform'], name='user_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['onboarding_stage'], name='user_onboarding_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stripe_customer_id'], name='user_stripe_cust_idx'),
        ),
    ]
