# Generated by Django 5.2.8 on 2025-11-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Platform-specific order ID', max_length=255)),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('bigcommerce', 'BigCommerce'), ('woocommerce', 'WooCommerce')], max_length=32)),
                ('customer_email', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(help_text='Order creation time on platform')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('line_items', models.JSONField(default=list, help_text='Order line items')),
                ('shipping_address', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict, help_text='Full platform response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(default=list, help_text='List of items being returned')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='returns.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='returns_ord_user_id_93dadc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform', 'external_id'], name='returns_ord_platfor_24899d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('external_id', 'platform', 'user')},
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', 'status'], name='returns_ret_user_id_31403f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['created_at'], name='returns_ret_created_a48112_idx'),
        ),
    ]
