# Generated by Django 5.2.8 on 2025-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='shopify_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
