# Generated by Django 5.2.8 on 2025-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_refund_amount_returnrequest_restock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='shipping_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
