# Generated by Django 5.2.8 on 2025-11-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('returns', '0004_returnrequest_is_gift_returnrequest_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='automation_rule_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_returns', to='automation.automationrule'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_flagged_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
