# Generated by Django 5.2.8 on 2025-11-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('APPROVE', 'Auto-Approve'), ('REJECT', 'Auto-Reject'), ('FLAG', 'Flag for Review')], default='FLAG', max_length=20)),
                ('trigger_field', models.CharField(choices=[('TOTAL_VALUE', 'Total Return Value'), ('RETURN_REASON', 'Return Reason'), ('ITEM_CONDITION', 'Item Condition')], max_length=50)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('contains', 'Contains')], max_length=20)),
                ('value', models.CharField(help_text="Value to compare against (e.g., '100' for $100, or 'Damaged' for reason)", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_high_velocity', models.BooleanField(default=True, help_text='Flag if customer returns too frequently')),
                ('max_return_velocity', models.IntegerField(default=3, help_text='Max returns allowed per month before flagging')),
                ('flag_high_value', models.BooleanField(default=True, help_text='Flag returns above a certain value')),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
