# Generated by Django 5.2.8 on 2025-11-27 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopifyinstallation',
            unique_together={('user', 'shop_domain')},
        ),
        migrations.AddField(
            model_name='shopifyinstallation',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful order sync timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinstallation',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopifyinstallation',
            name='shop_domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyinstallation',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='shopifyinstallation',
            name='installed_at',
        ),
    ]
